# Generated by Django 2.0.2 on 2019-08-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190830_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imageFun',
            new_name='image',
        ),
    ]
